name: build android unity plugin

inputs:
  backend:
    description: 'js backend'     
    required: true
  config:
    type: choice
    description: Release Or Debug
    options:
    - Release
    - Debug
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: Get backend artifact
      uses: ./.github/workflows/composites/unity-download-backend/
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        backend: ${{ github.event.inputs.backend }}
    - name: Install NDK
      run: |
        cd ~
        wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
        sudo apt install unzip -y
        unzip -q NDK
    - name: Build
      run: |
        cd unity/native_src
        ANDROID_NDK=~/android-ndk-r21b node make.js --platform android --backend ${{ github.event.inputs.backend }} --config ${{ github.event.inputs.config }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./unity/Assets/Plugins/**/*
        name: Unity_Plugins (${{ github.event.inputs.backend }}_${{ github.event.inputs.config }})