name: build windows unity plugin

inputs:
  backend:
    description: 'js backend'     
    required: true
  config:
    type: choice
    description: Release Or Debug
    options:
    - Release
    - Debug
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: Get backend artifact
      uses: ./.github/workflows/composites/unity-download-backend/
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        backend: ${{ inputs.backend }}
    - name: Build
      shell: powershell
      run: |
        cd unity\native_src
        node make.js --platform win --backend ${{ inputs.backend }} --config ${{ inputs.config }} --arch x64
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./unity/Assets/Plugins/**/*
        name: Unity_Plugins (${{ inputs.backend }}_${{ inputs.config }})