name: unity build plugins (custom backend)

on: 
  workflow_dispatch:
    inputs:
      backend:
        description: 'js backend'     
        required: true
      config:
        type: choice
        description: Release Or Debug
        options:
        - Release
        - Debug

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composites/unity-build-plugins/android.yml
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        backend: ${{ github.event.inputs.backend }}
        config: ${{ github.event.inputs.config }}
  ios:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composites/unity-build-plugins/ios.yml
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        backend: ${{ github.event.inputs.backend }}
        config: ${{ github.event.inputs.config }}
  osx:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composites/unity-build-plugins/osx.yml
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        backend: ${{ github.event.inputs.backend }}
        config: ${{ github.event.inputs.config }}
  windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composites/unity-build-plugins/windows.yml
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        backend: ${{ github.event.inputs.backend }}
        config: ${{ github.event.inputs.config }}
  linux64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composites/unity-build-plugins/linux.yml
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        backend: ${{ github.event.inputs.backend }}
        config: ${{ github.event.inputs.config }}