name: unity-unittest

on: 
  workflow_dispatch:
  push:
    paths: 
      - unity/Assets/**
      - unity/general/**
      - unity/native_src/**
      - unity/native_src_ourv8/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - .github/workflows/unity-unittest.yml
  
env:
  RUNID: 613573412

jobs:
  unittest-v8:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8'
      - name: Build plugin
        run: |
          md unity\general\Bin
          cd unity\native_src
          .\make_win64.bat
          copy build64_v8\Release\puerts.dll ..\general\Bin
      - name: UnitTest
        run: |
          cd unity\general\vs2013
          nuget restore Puerts.sln
          nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner -ExcludeVersion
          msbuild /property:Configuration=Release Puerts.sln
          ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe ../Bin/Puerts.UnitTest.dll   
  unittest-quickjs:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'quickjs'
      - name: Build plugin
        run: |
          md unity\general\Bin
          cd unity\native_src
          .\make_win64.bat quickjs
          copy build64_quickjs\Release\puerts.dll ..\general\Bin
          copy quickjs\Lib\Win64\*.dll ..\general\Bin
      - name: UnitTest
        run: |
          cd unity\general\vs2013
          nuget restore Puerts.sln
          nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner -ExcludeVersion
          msbuild /property:Configuration=Release Puerts.sln
          ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe ../Bin/Puerts.UnitTest.dll
          
  unittest-nodejs:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'nodejs'
      - name: Build plugin
        run: |
          md unity\general\Bin
          cd unity\native_src
          .\make_win64.bat nodejs
          copy build64_nodejs\Release\puerts.dll ..\general\Bin
          copy nodejs\Lib\Win64\*.dll ..\general\Bin
      - name: UnitTest
        run: |
          cd unity\general\vs2013
          nuget restore Puerts.sln
          nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner -ExcludeVersion
          msbuild /property:Configuration=Release Puerts.sln
          ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe ../Bin/Puerts.UnitTest.dll

