name: unity build plugins

on: 
  workflow_dispatch:
  push:
    paths: 
      - unity/native_src/**
      - unity/native_src_ourv8/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - .github/workflows/unity_build_plugins.yml

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8_9.4'
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          cd unity/native_src
          ANDROID_NDK=~/android-ndk-r21b node make.js --platform android --backend v8_9.4
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  android_qjs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'quickjs'
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          cd unity/native_src
          ANDROID_NDK=~/android-ndk-r21b node make.js --platform android --backend quickjs
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_QuickJS
  ios:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8'
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform ios --backend v8
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  ios_qjs:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'quickjs'
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform ios --backend quickjs
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_QuickJS
  osx:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8_9.4'
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform osx --backend v8_9.4
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  osx_node:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'nodejs_16'
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform osx --backend nodejs_16
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_NodeJS
  osx_qjs:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'quickjs'
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform osx --backend quickjs
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_QuickJS
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8_9.4'
      - name: Build
        run: |
          cd unity\native_src
          node make.js --platform win --backend v8_9.4
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  windows_qjs:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'quickjs'
      - name: Build
        run: |
          cd unity\native_src
          node make.js --platform win --backend quickjs
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_QuickJS
  windows_node:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'nodejs_16'
      - name: Build
        run: |
          cd unity\native_src
          node make.js --platform win --backend nodejs_16 --arch=x64
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_NodeJS
  linux64:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install libc++-dev
        run: |
          sudo apt-get install clang
          sudo apt-get install libc++-dev
          sudo apt-get install libc++abi-dev
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8_9.4'
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform linux --arch=x64 --backend v8_9.4
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
 